[tool.poetry]
name = "cstruct"
version = "0.1.0"
description = ""
authors = ["anthy-pc <anthy@10.0.0.13>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
